### ISSUE TITLE
Support transcode api

### ISSUE THREAD

**Issue by dthienphong** [andreia/php-sdk-dolby-api#3]
Your app is awesome! It would be great if you added transcode api. Thank you ❤️

**Comment by andreia** [comment]
Thank you @dthienphong I'm glad you liked it! ❤️

Sure, I'll work on it next weekend :)

**Comment by andreia** [comment]
@dthienphong Just merged it https://github.com/andreia/php-sdk-dolby-api/pull/4 :)

**Comment by dthienphong** [comment]
That's awesome, thank you so much 😍
